### ISSUE TITLE
City improvements pruchasing pre reqs

### ISSUE THREAD

**Issue by gjh33** [Vixaer/SettlersProject#28]
You should be able to still purchase a city improvement with a metropolis and no city HOWEVER. If no city is present you cannot purchase past the 3rd step since you need somewhere to place the metropolis. Game rules does not mention what happens if the metropolis is already placed so just assume you still need a city for the  4th improvement no matter what.

Of course no cities OR metros means no city improvements

**Comment by gjh33** [comment]
Also if you have a metropolis of a color, you should be able to continue upgrading that color regardless of your cities

**Comment by gjh33** [comment]
I can't upgrade any colors I got a metroplis for either

**Comment by ryanlanguay** [comment]
My old fix broke this, should work now
