### ISSUE TITLE
Double resources not awarded on city

### ISSUE THREAD

**Issue by gjh33** [Vixaer/SettlersProject#3]
See Commodities 4th paragraph:
https://en.wikipedia.org/wiki/Catan:_Cities_%26_Knights
Expected:
get 2 commodities and 2 resources

Actual:
get 1 commodity and 1 resource

Example:
https://gyazo.com/1a54fb051d333352619796fab31d6b3b
10 is rolled,
city should gain 2 wood and 2 paper
Instead it gets 1 of each

**Comment by ryanlanguay** [comment]
You misread the paragraph; you get 2 brick or 2 grain, but for the other three it's one resource and one commodity. It's in the rulebook really clearly too.

**Comment by gjh33** [comment]
Yup... You're right. Closing.
