### ISSUE TITLE
Barbarians

### ISSUE THREAD

**Issue by gjh33** [Vixaer/SettlersProject#32]
Check that knight strength is being counted not number of knights

On victory, player who gave the most strength is awarded one of 6 defender of catan cards. We can ignore this limit I'm sure. I doubt anyone will give a shit. But if you really wanna be thorough than it's just an int i guess.

If players tie, the players in the tie each draw a progess card from deck of their choice

**Comment by ryanlanguay** [comment]
Updated the methods for this
