### ISSUE TITLE
Losing longest road?

### ISSUE THREAD

**Issue by gjh33** [Vixaer/SettlersProject#33]
![image](https://cloud.githubusercontent.com/assets/7050512/24922634/01daa7b2-1ebd-11e7-9940-446b6a2c96c7.png)

Blue placed and road was lost, red placed and I got it back

another example

![image](https://cloud.githubusercontent.com/assets/7050512/24922659/18ff7418-1ebd-11e7-862d-b99a09450bde.png)

After placing another road:

![image](https://cloud.githubusercontent.com/assets/7050512/24922687/29abc99c-1ebd-11e7-9a6b-6455d3917a9b.png)

**Comment by ryanlanguay** [comment]
Fixed longest road logic
