### ISSUE TITLE
Possible to not get metropolis

### ISSUE THREAD

**Issue by gjh33** [Vixaer/SettlersProject#56]
If you are supposed to pick your metropolis but instead you choose to upgrade another city type and gain metropolis in that, it will override your previous one. We could just argue this is the players fault, it's w/e but might be worth a fix if it's quick. Otherwise ignore.

**Comment by ryanlanguay** [comment]
I think the fix for this would be non-trivial, so I'll suggest we blame the player; I don't know how fault-tolerant they want the game to be
